### ISSUE TITLE
商品詳細画面でサイズ変更の表記が違う

### ISSUE THREAD

**Issue by Kohei0309** [Kohei0309/ILEX-for-iOS#13]
* ボタンのタイトルを「M・L」→「サイズ変更」とする
* ピッカーの選択肢の名前を「M・L」→「（商品名）」にする
* サイズを変更した時、タイトル・写真・値段が変わること（一部は写真は変更しないが、URLは異なる。）

**Comment by kibok** [comment]
終了

**Comment by Kohei0309** [comment]
仕事早すぎｗｗ
