### ISSUE TITLE
アプリバージョンを「1.0」→「1.0.0」に変更

### ISSUE THREAD

**Issue by Kohei0309** [Kohei0309/ILEX-for-iOS#17]
- 設定画面では1.0.0と表記されているが、アプリの設定では「1.0」になっていた。
- 「1.0」→「1.0.0」に変更

**Comment by kibok** [comment]
終了

**Comment by Kohei0309** [comment]
@kibok 
変わってる？

**Comment by kibok** [comment]
@Kohei0309
俺のシミュレーターには前から 1.0.0 で出てる

**Comment by Kohei0309** [comment]
@kibok 
* アプリの設定の「1.0」は関係ない？

* コードから「1.0.0」が取得できればOK
    * http://qiita.com/nagatasci/items/7714281ab20ef5ddfede

**Comment by kibok** [comment]
@Kohei0309 
古い情報はリンクしても意味ないと思う。
やり方はわかるので次に実装します。

**Comment by Kohei0309** [comment]
@kibok 
Jsonを更新して再起動しましたが、出ませんでした。
明日確認しましょうー
