### ISSUE TITLE
アプリ初回起動時に利用規約に遷移させる

### ISSUE THREAD

**Issue by Kohei0309** [Kohei0309/ILEX-for-iOS#19]
- 初回起動時のみ利用規約に遷移を促すアラートを出す。
- メッセージ「アプリをインストールしていただきありがとうございます。当社はお客様のパートナーに最適な商品を提供しています。是非お試しください。\nまず最初に利用規約をご一読ください。」
- 選択肢「後で見る」or「利用規約へ」
- 利用規約へ→「利用規約画面を開く」
- 後で見る→「何もしない」

**Comment by kibok** [comment]
終了
