### ISSUE TITLE
アプリの情報を起動時に取得

### ISSUE THREAD

**Issue by Kohei0309** [Kohei0309/ILEX-for-iOS#20]
アプリの情報を起動時に取得
- 取得URL:http://itlife009.com/ILEX/config/state.json
- Jsonのバージョンと現在のアプリのバージョンが異なる場合にアラートを出す
- タイトル「アプリの最新版があります」
- メッセージ「(Jsonから取得するmessage)」
- 選択肢「AppStoreへ移動」

**Comment by kibok** [comment]
終了

**Comment by Kohei0309** [comment]
@kibok 
表示されず

**Comment by kibok** [comment]
今 1.0.0 で json も 1.0.0 からちゃう？
xcode 内でバージョン変えたら出てた

**Comment by Kohei0309** [comment]
@kibok 
Jsonを更新しましたが、ダメでした。
明日確認しましょう。
