### ISSUE TITLE
使い方画面について

### ISSUE THREAD

**Issue by Kohei0309** [Kohei0309/ILEX-for-iOS#21]
### 画面遷移
* 商品詳細ページ
* 使い方はこちら
* 使い方ページに遷移

### 仕様
* WebView
* URL:http://itlife009.com/ILEX/usage/{商品ID}.html

### 備考
* 現在は使い方ページが存在しないため、上記のURLを想定したロジックを組んでおく

**Comment by kibok** [comment]
終了
