### ISSUE TITLE
本番環境URLまとめ

### ISSUE THREAD

**Issue by Kohei0309** [Kohei0309/ILEX-for-iOS#22]
### アプリの情報
- http://itlife009.com/ILEX/config/state.json
### 商品情報
- http://itlife009.com/ILEX/item/ilex_part1.json
### WebView
- ライセンス
  - http://itlife009.com/ILEX/license/ios.html
- 利用規約
  - http://itlife009.com/ILEX/rule/index.html
- 商品の使い方
  - http://itlife009.com/ILEX/usage/{商品ID}.html
### メールAPI
- 注文
  - http://itlife009.com/ILEX/mail/order/ios.php
- メール登録
  - http://itlife009.com/ILEX/mail/register/ios.php
### 画像リソース
- {商品画像URL}

**Comment by kibok** [comment]
終了

**Comment by Kohei0309** [comment]
@kibok 
これはちょっと確認用で置いときます。
