### ISSUE TITLE
注文確認メールで正しく項目が入っていない

### ISSUE THREAD

**Issue by Kohei0309** [Kohei0309/ILEX-for-iOS#27]
- メール上部の「〜〜　様」に名前が入っていない（山田太郎　様」のようにする）
- 注文番号が入っていない

**Comment by kibok** [comment]
終了

**Comment by Kohei0309** [comment]
@kibok 
注文番号が入っていません

**Comment by kibok** [comment]
@Kohei0309
注文番号がどこから取得するのかわかりません。

**Comment by Kohei0309** [comment]
@kibok 
乱数７桁をアプリの方で、作る
・乱数をメールで送る
・注文履歴モデルにもたせておく
