### ISSUE TITLE
サイズ変更ボタンを押した時、テキストがフォーカスされる

### ISSUE THREAD

**Issue by Kohei0309** [Kohei0309/ILEX-for-iOS#28]
サイズ変更ボタンを押しても、テキストにフォーカスが当たらないようにする。

**Comment by kibok** [comment]
テキストにフォーカスが当たらない方法がわかんない。
後でいい方法が見つかったら直してください。

**Comment by Kohei0309** [comment]
@kibok 
了解です。ありがとう。

**Comment by Kohei0309** [comment]
@kibok 
サイズ変更のピッカーを閉じる「Done」ボタンどこいった！？
