### ISSUE TITLE
Alert を アンドロイドと合わせる

### ISSUE THREAD

**Issue by kibok** [Kohei0309/ILEX-for-iOS#3]
Alert を アンドロイドと合わせる

**Comment by kibok** [comment]
出てないアラート教えてください

**Comment by Kohei0309** [comment]
@kibok 
確認します

**Comment by Kohei0309** [comment]
@kibok 
* メール認証画面で、「メールが届かない」を押した時に出すアラート
    * タイトル「メールが届かない場合」
    * メッセージ「1.メールアドレスをもう一度間違っていないか確認してください。\n\n2.ドメイン設定をされている場合は設定を変更してください。このアプリから送られるメールアドレスのドメインは「ilex.ac」です。」
    * （\nはEnter）

**Comment by kibok** [comment]
終了
