### ISSUE TITLE
今後の作業について

### ISSUE THREAD

**Issue by kibok** [Kohei0309/ILEX-for-iOS#30]
ある程度の作業は終わったと思う。
案件で平日時間が取れないし自分の作業が遅いので週末も案件する可能性が高い
なので今後の作業はお願いします。
これぐらいだと 5000 円分の仕事は終わったと思うので。

**Comment by Kohei0309** [comment]
@kibok 
はい、また質問等は聞くと思うので
よろしくお願いします。ありがとうございました。

**Comment by Kohei0309** [comment]
@kibok 
ありがとー。また焼き肉いきましょう。
